name: build DAE

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH连接'
        required: false
        default: 'false'
      branch:
        description: '编译特定分支'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [ '1.23.0' ]
    
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: SSH Connection to Actions
        if: (github.event.inputs.ssh == 'true' || contains(github.event.action, 'ssh'))
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          USER_PASS: ${{ secrets.USER_PASS }}
        run: |
          # 安装ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
          unzip ngrok.zip
          chmod +x ngrok
          ./ngrok authtoken $NGROK_TOKEN
          
          # 设置SSH
          sudo apt-get install -y openssh-server
          echo "### Update user: $USER password ###"
          echo -e "$USER_PASS\n$USER_PASS" | sudo passwd "$USER"
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart
          
          # 启动ngrok隧道
          rm -f .ngrok.log
          ./ngrok tcp 22 --log ".ngrok.log" &
          sleep 10
          # 检查是否有错误
          HAS_ERRORS=$(grep "command failed" <.ngrok.log)
          
          if [[ -z "$HAS_ERRORS" ]]; then
            echo ""
            echo "=========================================="
            echo '连接: '"$(grep -o -E 'tcp://(.+)' < .ngrok.log | head -n 1 | sed 's/tcp:\/\//ssh '"$USER"'@/' | sed 's/:/ -p /')"
            echo "=========================================="
          else
            echo "$HAS_ERRORS"
            exit 4
          fi
          
      - name: Build Go
        env:
          BRANCH: ${{ github.event.inputs.branch }}
        run: |
          set +e
          sudo apt-get update 
          sudo apt-get install -y llvm-15 clang-15 git make
          export CLANG=clang-15
          
          # 克隆仓库 - 修复了分支克隆的逻辑错误
          if [ -n "${BRANCH}" ]; then
            git clone https://github.com/daeuniverse/dae.git -b ${BRANCH} dae
          else 
            git clone https://github.com/daeuniverse/dae.git dae
          fi
          
          # 执行构建
          cd dae
          make OUTPUT=dae-amd64 GOFLAGS="-buildvcs=false" CC=clang CGO_ENABLED=0
          echo "DIR_NAME=$PWD" >> $GITHUB_ENV
  
      - name: Bump Version and Push Tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Upload Go to Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          files: ${{ env.DIR_NAME }}/dae-amd64

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3

      - name: Remove Old Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
